### ISSUE TITLE
[Feature request] It would be better to add export and import session functions

### ISSUE THREAD

**Issue by ttbadr** [kingToolbox/WindTerm#161]
This app is the best terminal I want for now. Here are some ideas for your consideration:
1. export sessions and quick commands, import them to other devices
2. is any chance to supports to import xshell session or dev an import function that could imports some struct text file like below to supports batch import sessions, It's convenient for people who want to move from other apps:
  ```
  group:
      session1:
             host:
             user:
       session2:
             host:
             user:
  ```
3. set authentication method on the group, if the sessions under the group no authentication method specified, then use the group one.
